### ISSUE TITLE
stylesheet is not a recognized Liquid tag

### ISSUE THREAD

**Issue by andremeireles** [mmistakes/made-mistakes-jekyll#1]
I forked the project to test like gh-page but Github show me the following message.

Github Settings : Your page is having problems building: The tag stylesheet in _layouts/default.html is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error.

**Comment by jeexianwu** [comment]
I met the same issue.

**Comment by mmistakes** [comment]
My Jekyll setup isn't GitHub Pages compatible. I'm using several [Jekyll plugins](http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html) and that's why you're getting the errors.

If you want to use my repo as a base you'll need to self hosted like I do. Or you could build the site locally and just push the contents of `_site` to GitHub if you want to take advantage of their free hosting.

**Comment by andremeireles** [comment]
Thank you for explain. I'll do it.
