### ISSUE TITLE
favicon - Some pages have, other doesn't.

### ISSUE THREAD

**Issue by andremeireles** [mmistakes/made-mistakes-jekyll#2]
For example:

[Masterpaper - Mix](https://mademistakes.com/mastering-paper/mix/) - **have favicon**
[Masterpaper - Basics](https://mademistakes.com/mastering-paper/basics/) - **doesn't have favicon**

and so on...

I saw a few examples building my website.

**Comment by mmistakes** [comment]
Weird. There's nothing different between those pages that would case it to show on one or the other. I know I've seen browsers do strange things with favicons but usually it fairly binary, they either work or they don't. For me the both show fine in Chrome and Safari on both of those pages.

You have any sort of Adblock plugins installed? No idea if that's the issue here but I wouldn't be surprised because every time I get an issue filed about icons not showing it's always the fault of an over zealous extension or plugin.

**Chrome:**
![screen shot 2015-03-10 at 11 24 33 pm](https://cloud.githubusercontent.com/assets/1376749/6589795/b99c6358-c77c-11e4-82a7-70b3dd650b30.png)

**Safari:**
![screen shot 2015-03-10 at 11 25 32 pm](https://cloud.githubusercontent.com/assets/1376749/6589814/0f3f06a8-c77d-11e4-9522-f861f4d94b6e.png)
![screen shot 2015-03-10 at 11 25 58 pm](https://cloud.githubusercontent.com/assets/1376749/6589815/112d767a-c77d-11e4-855c-929ca42691da.png)

**Comment by andremeireles** [comment]
Yeah, i have an Adblock.
Everything works great now!
Thank you very much.

**Comment by mmistakes** [comment]
Adblock... it'll git cha everytime.
