### ISSUE TITLE
Section backgrounds location and lazy loading images (only loading upon mobile device change in orientation)

### ISSUE THREAD

**Issue by pateskinasy** [mmistakes/made-mistakes-jekyll#688]
Hi Michael!

Two issues I'm hoping you'd have some quick pointers for:

1) I've been going through all SCSS and CSS (changed the `_variables.scss` a lot) and can't find where the backgrounds for the sections (the solid ones that show up when there is no background image for sections, e.g. In your case: purple for "Work") are coming from. Any pointers here? Browser Dev tools are really not helping me here.

So, I'm aware you have `$section-work-bg-color: mix(#000, #6e2364, 50%);` which is purple... in my case however, I have `$section-work-bg-color: mix(#262626, #2a201b, 50%);`, which is _blackish_ but I keep getting your purple background upon build.

2) Your images are snappy-loading on mobile. My images are only loading on mobile if I change mobile device reorientation (from portrait to landscape), that kicks in the loading and _only_ then they show-up on portrait orientation. Something to do with the lazy loading I guess, but I haven't touched that code at all yet...Any pointers?

Super thanks a ton in advance!

**Comment by mmistakes** [comment]
1. Check the YAML front matter in [`index.md`](https://github.com/mmistakes/made-mistakes-jekyll/blob/master/src/index.md), all of the section images are assigned there.

2. Which images? If you're talking about the large feature images on posts/pages then there's a chance you haven't created all of the variations. I have a Gulp task that goes through and [resizes a high res image into multiple resolutions](https://github.com/mmistakes/made-mistakes-jekyll/blob/master/gulp/tasks/images.js#L45-L67) so they can be loaded responsively via [`srcset` markup](https://github.com/mmistakes/made-mistakes-jekyll/blob/master/src/_includes/page__cover.html#L11-L19).

Sounds like you're missing a few and that's why you don't see anything until you change the device size that matches images you actually have.

**Comment by pateskinasy** [comment]
Hi @mmistakes,

1. My trouble on point 1 is not with the images (those I've changed), but with the section backgrounds. I'm referring to the solid purple background (for your `Work` section) that gets loaded when no image is loaded. Please see image showing what background I'm referring to on mademistakes.com https://ibb.co/7z2BCWj

My guess is that this comes from your `$section-work-bg-color: mix(#000, #6e2364, 50%)` which is purple. But I've changed mine to `$section-work-bg-color: mix(#262626, #2a201b, 50%)
` which is black, but I still get your purple rendered (strangely enough)

2. On point 2 my trouble is with the section images I've added on `index.md`. My images do not load on mobile (they only do after a change in device orientation). Yes, I have not created all variations. I have simply added them to /assets/images and let gulp build. You can see results prior https://ibb.co/y6tLGmj and post change in orientation https://ibb.co/bzZBZSv in attached images from my website.

Following your note, I've moved the images to a new folder I've created /assets/images/feature in the hope `gulp` would deal with them (I've obviously changed the path in index.md as well to /assets/images/feature) but then I get no pictures rendered whatsoever. See image from m y website https://ibb.co/y6tLGmj

So, are there other changes in javascript I need to do to get gulp to find those images?

**Comment by mmistakes** [comment]
1. Uses a gradient mixin on the `:before` element that overlays the image. The line you need to change is this one. Either change the gradient colors or remove it.

https://github.com/mmistakes/made-mistakes-jekyll/blob/master/src/assets/stylesheets/_sections.scss#L175-L177

Not sure on 2. My site is extremely custom and isn't released as a theme. It's 100% a work in progress so you're kind of on your own if you decide to fork it ;-)

**Comment by pateskinasy** [comment]
Thanks for the fast response @mmistakes 

On 2. Yes, I'm aware you haven't released it as a theme. I know I'm forking on my own risk. Further note on this point, I've now replicated your setup with a separate repo for images (and now everything works well on `http://localhost:4000/` but netlify is not liking it and is not picking up the images on the separate repo. I'll go to the netligy community to try to getting some support as this seems to have to do with them. 

On 1. yes, I had seen ```
&::before {
        @include scrimgradient("to right", $section-work-bg-color);
      }
```
my issue here is: my `$section-work-bg-color` is not purple (like yours is). Mine is a hue of black (I had changed the gradient colors). So the gradient for me should be in shades of black. I have no idea where the code is getting that purple hue from (your purple)...

Will explore further and should I find anything I'll report here for others. :)

**Comment by mmistakes** [comment]
There's one other part to the CSS. I'm inlining the critical CSS to improve load performance. So even though you change the Sass variables, you're still likely using my inlined CSS that has the purple gradients (and other styling you may have changed).

You'll need to clear out the inlined CSS `_includes` (don't delete them since Jekyll will complain).

![image](https://user-images.githubusercontent.com/1376749/57702932-04f0b300-762d-11e9-9e41-47ebdeec8935.png)

Once you've gotten the styling sorted you can run the Gulp task to recreate them.
https://github.com/mmistakes/made-mistakes-jekyll/blob/master/README.md#gulp-critical

**Comment by pateskinasy** [comment]
BINGO!!!!!

Now I'll need to make netlify find the images in the separete github repo. 

Will report when I fix it!

Thanks @mmistakes !

**Comment by pateskinasy** [comment]
For others struggling with imagery lazy loading, this is how I've solved the problem: Kept imagery in separate repo (just like in Made Mistake's case), created a git submodule for the imagery repo and gave Netlify access to the imagery repo (via deploy keys).
